package.json

If you skipped the dots on purpose, just close this pull request. I'd keep them, because every URL on GitHub will keep the dot.

fixed urls and name

---

css/locationbar.css
src/browser/navigation-panel.js

Switching between ssl and non-ssl page makes the navbar jumbs a bit.
@gordonbrander, can you review this?

Fix ssl character alignment

---

css/tabstrip.css
src/browser/page-switch.js

Fixes https://github.com/mozilla/browser.html/issues/64
Also increases interactable area of thumbnails.
Note that I first tried using only CSS (`::after` and `attr()`) to solve this problem, but our support of CSS generated is too limited to pull this off. So instead, I added an element.

Fix interactable gap between thumbnails

---

src/browser/browser.js

Even if there is only one website. Closes
https://github.com/mozilla/browser.html/issues/131.

Always show tab strip on location hover

---

src/browser/browser.js

Just noticed that react seems to handle `title` attribute on it's own & that our hooks aren't invoked. Fixing it so that document.title will actually gets updated.

Fix app title

---

css/locationbar.css
src/browser/iframe.js
src/browser/navigation-panel.js
src/browser/progressbar.js
src/browser/theme.js
src/browser/web-viewer.js
src/browser/web-viewer/actions.js

issue #72. Please only look at the last commit (`wip`).
This is still WIP. But I need to know if this is the right approach.
Here is how it works:
The progressbar is split in 3 zones: **`[ aaa bbbb ccccccc]`**.
Zone **A** (~10% of the locationbar), is blue as soon as we start loading a page.
Zone **B** (~40% of the locationbar), is slowly incremented as the page is loading (see explanation below).
Zone **C** (~50%, rest of the locationbar), is filled once the page is fully loaded.
Zone **B** is updated every time gecko tells us there's a progression. But we *do not* use at the values of the progress event (see #72). So the bar moves only if there's activity, and its position is defined by a invert tangent function of loading time, which means as time pass, less and less pixels are added …

better progressbar

---

css/locationbar.css
css/navbar.css
src/browser/progressbar.js

This approach is pretty generic, but solves a lot of the color matching
issues. Could use as an interim fix. Fixes
https://github.com/mozilla/browser.html/issues/115 and
https://github.com/mozilla/browser.html/issues/152

Move progress bar below tabstrip

---

main.js
src/browser/actions.js
src/browser/browser.js
src/browser/deck/actions.js
src/browser/keyboard.js
src/os.js

- Remove obsolete deck actions.
- Generate diff bindings based on platform.

Make tab switching multi-platform

---

src/browser/browser.js

https://github.com/mozilla/browser.html/wiki/Design-F.A.Q.#q-how-to-avoid-recomputing-derived-state-on-each-update-

Take advantage of caching API to avoid extra computations.

---

src/browser/actions.js
src/browser/browser.js
src/browser/deck.js
src/browser/deck/actions.js
src/browser/page-switch.js
src/browser/web-viewer.js

**P.S.:** This change depends on new fields in data model so in order for you tabs to start render in right order you'd need to activate each one or reset session with `cmd shift backspace`

Implement tab ordering by switch time.

---

css/tabstrip.css

Pragmatic fix. Remove tabstrip hide/show transition. I think this improves the interface by making it feel more responsive anyway.
We keep the animation on `.tabstripkillzone`, but give it a gentler transition. This prevents the opacity change of `.tabstripkillzone` from drawing the eye when the tabstrip should be center of attention..
Fixes #204.

Fix #204 by removing transition

---

src/browser/browser.js
src/browser/page-switch.js

Assumes that is landed #220 so only relevant changes are these https://github.com/Gozala/browser.html/compare/thumbnails...Gozala:tab-switch-order

Tab switch order

---

css/tabstrip.css
src/browser/page-switch.js

Initial new tab style. It's not perfect, but it's better than what we had.
We unified the concept of "dashboard", "new tab", "add tab" into a single model. I prefer the "+" analogy to something like a home icon because it is the most immediately aligned with a new user's interest ("I want a new tab"), with the discovery of the dashboard being a happy result.

Add new tab style

---

src/browser/actions.js
src/browser/browser.js
src/browser/editable.js
src/browser/navigation-panel.js

Sometimes you can end up in broken state where escaping the address bar is impossible. I believe it could be reproduced by pressing `cmd l` while in the location bar. I think this is also what issue #264 is about, but I maybe wrong.
Either way current problem is that keyboard shortcut will store `selection` state into a state that later is used to update selection in the input. The problem was that changes to the selection were never reflected in the state there for any re-render would select all of the text in the input over and over.
This patch cleans up a little how selection was implemented (it was hacked together without much of a thought) and wires both ends so that changes to selection are reflected in the state and changes in the state are reflected in the UI.

Selection state should be updated both ways.

---

src/browser/browser.js

Fixes https://github.com/mozilla/browser.html/issues/271
@Gozala I can also put together a follow-up that factors out `remove(items, p)` into `findAndRemove(items, p)` and `remove(items, item)`. That would be marginally more efficient since we wouldn't have to `find` twice.

Prevent closing dashboard via cmd+w

---

css/locationbar.css
src/about/settings/index.html
src/about/settings/index.js
src/about/settings/main.js
src/about/settings/settings.css
src/browser/actions.js
src/browser/element.js
src/browser/github.js
src/browser/iframe.js
src/browser/navigation-panel.js
src/browser/util/url.js
src/browser/web-viewer.js

This comes with 2 commits:
* Support for `about:*` urls. `about:foobar` will load `http://…/src/about/foobar/index.html` in a privileged tab, which has the same privileges as browser.html.
* `about:settings` page. Just dump the settings. Very basic, but will be useful to check versions & co.

Basic support for about:setting

---

README.md
package.json

Let's fully leverage `npm` + `node`  setup and kill dependency on python and SimpleHTTP.

Use ecstatic instead of python SympleHTTPServer

---

src/browser/actions.js
src/browser/iframe.js
src/browser/navigation-panel.js
src/browser/web-viewer.js
src/browser/web-viewer/actions.js

This is related to discussion in #250 regarding a webview state simplification that drops `location` field in favor of `uri`.
This change basically moves hack from web view into iframe which is required to avoid changing a `iframe.src` if new value matches curretly loaded content `uri`.

Unite location and uri into single field.

---

src/browser/web-viewer.js

Currently there are bunch of issues caused by `readyState` field not being reset, for example if you do refresh twice second one is ignored that's because `readyState` value will be `refresh` instead of `loaded`. Similar issues happen with `goBack` `goForward`.

Reset readyState to fix repeated commands.

---

.gitignore
README.md
package.json
test/mocha.opts
test/new_tab_test.js
test/runall.sh

This is using some forked b2g testing packages here: https://github.com/kevingrandon/graphene-marionette-runner
It's still a bit rough around the edges, but should give you an idea of how things could work. Next up would be importing the node http servers from gaia to serve static content from a fixtures directory.

Basic integration test support.

---

src/browser/browser.js

Hitting delete key will jump back to previous page in tab history.

Add backspace-to-go-back command

---

src/browser/browser.js

This reverts commit 030a5b980445ff98f662ef2e7f2c01de0fd9589e, reversing
changes made to 9b09de3723e5124c6f2cc0fe089afdb28979fbaa.
Temporarily backing this out to work around https://github.com/mozilla/browser.html/issues/432 until platform fix lands and we can build a better solution.

Revert "Merge pull request #429 from gordonbrander/backspace-back"

---

src/common/runtime.js

Runtime support was added here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1181232

Remove CleanRestart from unsupported actions

---

css/animations.css
index.html
src/browser/browser.js
src/browser/location-bar.js
src/browser/progress-bar.js
src/browser/web-view.js

Instead of having one single progressbar, here, I build one progressbar per webview. That allows us to keep the `translateX` position when switching tabs. With some transition and animation magics, we can reproduce the previous behavior.
The result is a much smoother animation.
Maybe the progresssbar should be built outside of the webview.
I'm wondering if passing the theme into the webview then to the progressbar is a problem (iirc, we had some issues because of that earlier).
I renamed Progress to WebProgress just to make my life easier when doing the rewrite. We can keep it that way or go back to Progress(bar).

Use CSS to animate progressbars

---

src/service/scraper.js

This should have been the case from the beginning.

Favor title over heading

---

src/browser/web-view.js

...and get rid of transition origin when scaling. If we want to set an origin on scaling, we have to be much smarter and take into account CSS centering as well as scroll position.
This is a temporary workaround for https://github.com/mozilla/browser.html/issues/488 that improves the situation a bit but does not solve the issue.

Fade in when dashboard -> webview

---

src/browser/browser.js
src/browser/theme.js
src/browser/web-view.js
src/service/pallet.js

Fixes https://github.com/mozilla/browser.html/issues/467. Fix hardcoded color themes and themes generated using `theme-color`.
Will eventually follow up with a PR that bases themes on `background-color` instead of `theme-color` meta tag.

Fix color themes

---

src/browser/web-view.js

Fixes https://github.com/mozilla/browser.html/issues/468
Do so by prepending models with `.unshift()` instead of `.push()`, per comment https://github.com/mozilla/browser.html/pull/487#issuecomment-121433663

Model webviews LTR, newest to oldest

---

src/browser/browser.js
src/browser/synthesis-ui.js
src/browser/web-preview.js
src/browser/web-view.js

Fix for https://github.com/mozilla/browser.html/issues/488.
In this version, we have a `mode` field and a `transition` field in the model.

Tailor mode transitions (take 2)

---

src/service/suggestion.js

4 seconds is too long. We end-up with strange results.

suggestion throttle time is too big

---

src/browser/web-view.js

Cmd-Click doesn't open links in background anymore. Regressed because of #497.

fix cmd-click

---

src/browser/web-view.js

Other wise, pressing Cmd-W brings you to the older tab, which is weird.

select younger tab on close

---

src/browser/web-loader.js
src/browser/web-view.js

It's an unnecessary constrain. If I want to open empty pages for example, this makes it impossible.

make loader uri optional

---

src/browser/location-bar.js

Fix for #486
So issue is related to selection state, which is set to `{start: 0, end: Infinity}` when we select all of the input. Although if such app state is stored it causes `JSON.serialize({start: 0, end: Infinity})` to run that produces `'{start:0, end:null}'` which is invalid state, given that `selection.end` is declared to be a number not a `null`.
Solution is to react to `selection` events and update state when the happen (please note that this was a case prior to refactoring, the fact that it is no longer a case was unintentional). Now with this change when we update selection by setting it to `{start: 0, end: Infinity}` that causes a `selection` event that will contain integer value for `selection.end` which is then stored into state, which in turn avoids an outlined bug caused …

Fix session restore bug

---

src/browser/location-bar.js

I'm afraid I have introduced regression in #548 that breaks suggestion-box as it sends change events whenever selection changes. I think suggestion engine needs a deeper changes, but this does solve an issue right now so it's worth doing it and rethink how we deal with suggestion later on.

Properly handle selection change.

---

src/browser/browser.js
src/browser/location-bar.js

`F12` is taken by OSX by default, there for I'm adding another keybinding that matches regular devtools key binding on all browsers.

Devtools shortcut

---

src/service/scraper.js

Babel replaces all uses of `Promise` to `require('babel-core/runtime').Promise` that is either native promise or polyfill. This introduced a regression as we use `scraper` function with `Promise(...)` as `iframe.executeScript(scraper + '()')` which now breaks as `Promise` there will be replaced with `require('babel-core/runtime').Promise` and in the context it's run there is no `require`. Fix simply changes use to `window.Promise` so babel won't replace it and there for we won't run into this issue.

Fix scraper to make it use promise properly.

---

src/browser/iframe.js
src/browser/web-page.js
src/browser/web-view.js
src/service/pallet.js

This is imperfect fix for #536 that resets state of the page card only on location change if the location has changed, but keeps the color pallet unless domain has changed.

Keep the color pallet across domains.

---

src/browser/web-preview.js

This adds scroll snapping to tab cards. Fixes https://github.com/mozilla/browser.html/issues/558.
@paulrouget The physics don't feel quite right on Desktop. Let's see if we can tweak the platform.

Add scroll snapping

---

src/browser/iframe.js
src/browser/index.js
src/browser/web-loader.js
src/browser/web-view.js
src/common/element.js
src/service/force.js

This is very hacky fix that has to workaround ton of issues, here is little overview:
- Workaround #566 and present desired API by boxing frame in a string instance that is later unboxed by an IFrame react component.
- Workaround #567 by setting a flag on iframe so that implementation of `IFrame` won't call `zoom` on it.
- Workaround #568  by setting a flag on iframe so that implementation of `IFrame` won't call `setVisible` on it. 
- Workaround #564 by creating a type `Force.Action` so that actions boxed with it will force render loop to run sync in the same tick.

Shameful fix for #475 that makes me feel guilty.

---

src/browser/web-preview.js

Fixes https://github.com/mozilla/browser.html/issues/578.
We should re-introduce the card title in card contents if we can get the
scraper to return good results for content headings.
@paulrouget r?

Show title in card header

---

package.json

Removes the following warning:
```
npm WARN package.json browser.html@0.0.8 No license field.
```
More info here:
https://docs.npmjs.com/files/package.json#license

Migrate to new package.json license format

---

package.json
src/browser/browser.js
src/browser/web-sheet.js
src/browser/web-view.js
src/common/animation.js

@gordonbrander this is an attempt to implement page slide based go back / forward, but unfortunately it's unusable as screenshots arrive just too late, usually when the sliding page is about slide out of viewport. And when it does it render image it causes junk.
P.S.: I have not actually hooked up navigation events because idea was to trigger goBack after we have a screenshot but this just unusable to be worth finishing.
Related to #646

Implement page slide based navigation.

---

package.json

Upstream packages were finally updated to have support for node 4/5.
Let's see what this does on travis.

Update testing packages.

---

src/browser/browser.js
src/browser/perspective-ui.js

This gives us the structure we'll need to implement modes in `PerspectiveUI.view`.

Move children of Browser.view out to PerspectiveUI

---

src/driver/virtual-dom/index.js

We used target.ownerDocument.documentElement for event binding, since
servo doesn't yet bubble events to window. However,
target.ownerDocument.documentElement does not receive window focus/blur
events, which we need for windowcontrols.
This commit switches to target.ownerDocument for event binding in the
hopes that this will work for Servo. I'm not sure how to test that.
cc @paulrouget

Bind events to target.owner document

---

src/browser/perspective-ui.js

Keeps it from peeking out on large screens (artifact of rotation and
perspective).

Push sidebar further right

---

src/browser/input.js

@paulrouget use of keyup event seems to have some issues when typing fast (one you mentioned in the meeting) but even on gecko. I get an impression that when `keyup` is fired `input.value` has not yet changed, but it maybe something different. I'll try to work it out what happens tomorrow, but for now you can try merging this for testing on servo if you like.

Use keyup event instead of input event for observing input updates.

---

src/browser/perspective-ui.js

We convert the webview action to a Browser action, since it's actually an action for browser (clearing the input) and not webviews.

Clear new tab input when clicking + button

---

src/browser/perspective-ui.js
src/browser/sidebar.js
src/browser/sidebar/toolbar.js

This cleans up many of the animation details for `show-tabs -> show-webview` when pinned.
- Tabs are animated to their "mini" version
- Sidebar toolbar is faded out
Still todo
- Set width of suggestions box to width of webviews
- Show hamburger menu and + button in pinned sidebar (not webview)
Going to address the last 2 in follow-up PRs as they require some markup restructuring.

Separate animation for show-tabs -> show-webview when pinned

---

src/browser/perspective-ui.js

This lets us set the div's width when pinning the sidebar, so everything lines up correctly.

Wrap webviews, overlay, suggestions, input in common div

---

src/browser/updater.js

Followup for #809. Without this change Errors are logged on browser initialization.

Fix assertion of local host.

---

src/browser/input.js

Fixes https://github.com/mozilla/browser.html/issues/826.
- Move icon padding from input wrapper to input. This won't fix the dotted focus line in Servo, but it will at least make it wrap around the input instead of a random box.
- Add focus border to input.

Fix input styles

---

src/browser/browser.js
src/browser/perspective-ui.js
src/browser/sidebar.js
src/browser/sidebar/tab.js
src/browser/sidebar/tabs.js

Fixes #849 
Clicking tab close button was triggering `onMouseDown` of the tab container triggering `TabSelect` action that was starting an animation & as a consequence `onClick` on close button was no longer triggered which cased unreliable tab closing behavior.
As a matter of fact `Select` action was not required and was more of leftover from post refactoring codebase.

Do not select tab on close button click.

---

src/browser/sidebar/tab.js

This prevents tab from triggering TabActivate action when tab’s close button is clicked.
Fixes #852

Stop propagation of events in close button

---

src/browser/web-view.js
src/browser/web-views.js

This fixes both `cmd click` and `window.open`. Fixes https://github.com/mozilla/browser.html/issues/857#issuecomment-176960517.

Open new tabs on link click

---

src/browser/web-views.js

I think current behavior of entering screen with no web-view is kind of odd, so this patch just enters `create-web-view` mode if last tab is closed. 
@gordonbrander Feel free to land or tell me that we should do something else here.

Enter create-tap page once last tab is closed.

---

gulpfile.babel.js
index.html
package.json

Under Cargo this outputs the dist directory under Cargo's $OUT_DIR. It
uses an added --dest commandline option to achieve this.

Cargoify browser.html

---

src/browser/web-view.js

This is a temporary measure to work around the lack of gestures for
forward/back. Fixes https://github.com/browserhtml/browserhtml/issues/926.

Add back button

---

src/browser/web-view.js

Overscroll shows the background color of the iframe.
We want this to match the titlebar color.
Fix #934

change iframe background color

---

package.json

This resolves the issue for cases where user might have multiple versions of flow installed. Different versions may fail to type check.

Add `npm run status` to check flow status.

---

.flowconfig
src/about/newtab/main.js
src/about/repl/main.js
src/about/settings/main.js
src/browser/index.js

Turns out new babel no longer polyfills Promises by default. It also seems turns out that we don’t have promises on servo. This changes includes polyfill to have Promises in Servo.

Include babel-polyfill

---

src/common/runtime.js
src/common/runtime.js.flow

Runtime.quit -> window.close()
Runtime.reload -> window.location.reload()
Runtime.cleanReload -> Runtime.location.reload(true)
Fixes #944 Depends on #957

Handle window close/reload diff on servo

---

package.json

This fixes regression I introduced #957, where I forgot to include babel-polyfill into dependencies.

Add babel-polyfill to devDependencies

---

src/browser/web-view/progress.js

Before `display.x` was changing from 1 to 0 and when progress idle `display.x` was set to 0 which meant seeing full progress bar. This change reverses meaning of x so it grows from 0 to 1.
Fixes #928

Fix brief appearance of full length progress bar.

---

src/browser/web-view.js
src/browser/web-view.js.flow
src/browser/web-view/navigation.js
src/browser/web-view/navigation.js.flow
src/browser/web-view/util.js
src/browser/web-view/util.js.flow

@Gozala can you review this? I didn't remove the Gecko `canGoBackChanged` code path, but augmented it.
@paulrouget This works in Gecko, but I see no change in Servo. For Servo we should have `canGoBack` and `canGoForward` in `event.detail` (per https://github.com/servo/servo/commit/6577409b95bc782c0493cc5186fa4ed0d31d680d), but the latest servo-binary build doesn't seem to have this feature yet?
Fixes https://github.com/browserhtml/browserhtml/issues/941.

Hide back button if you can't go back

---

css/theme.css

Servo just added support for the `::selection` pseudo element, but doesn't include default value. Let's add this to our stylesheet.

add ::selection colors

---

src/browser/web-view/progress.js
src/browser/web-view/progress.js.flow

Progress.update was checking if new progress value was < 1 and increment progress or stop requesting frames and put progress to idle. Somehow on servo we still were getting extra update initiated by RAF in which case progress would be 0 we end up with restarted loop but this time it would never end since status remained idle and in that case we compute progress as 0.
This change makes sure that ticks on idle progress bar are ignored & there for no more new frames are requested.
Fixes #976

Fix endless RAF loop caused by web-view/progress.js

---

src/browser/web-view.js
src/browser/web-view.js.flow
src/browser/web-views.js
src/browser/web-views.js.flow

This is a simple implementation of "force touch to show tabs".
This PR does **not** attempt to use `servoMouseForceChanged` to follow force 1:1. Instead, it uses a fixed-duration animation. This is because animation code for show-tabs transition assumes hard-coded duration, and will require some non-trivial refactoring. I suggest that we merge this PR first, then do a follow-up PR.
This PR fixes some problems with https://github.com/browserhtml/browserhtml/pull/946.
Fixes https://github.com/browserhtml/browserhtml/issues/872.
cc @paulrouget.

Implement basic force-push to show tabs

---

main.js
package.json
src/browser/browser.js
src/browser/sidebar/tab.js
src/browser/sidebar/toolbar.js
src/browser/web-view.js
src/browser/web-view.js.flow
src/browser/web-view/electron-frame.js
src/browser/web-view/moz-browser-frame.js
src/browser/web-view/security.js
src/browser/web-view/security.js.flow
src/browser/web-view/shell.js
src/browser/web-view/shell.js.flow
src/browser/web-views.js
src/common/keyboard.js
src/common/runtime.js
src/common/runtime.js.flow
src/common/style.js
src/common/style.js.flow

With this changes you can run browser.html on top of Electron. To do so you need, to:
1. Install electron on your machine. You can do it by running `npm install -g electron-prebuilt`
2. Run browser.html on top of Electron from project root via command `electron .`

Make browser.html usable on electron.

---

src/common/runtime.js
src/common/url-helper.js
src/common/url-helper.js.flow

- WebKit does not even have `window.URLSearchParams` so attempt to construct was throwing an error.
- Servo does no implement iteration protocol for `URLSearchParams[Symbol.iterator]` so attempt to iterate was throwing.
Fixes #985

Avoid errors on incomplete URLSearchParams implementations

---

src/browser.js
src/browser/web-view.js
src/browser/web-view.js.flow
src/browser/web-view/electron-frame.js
src/browser/web-view/moz-browser-frame.js
src/browser/web-views.js
src/driver/virtual-dom/index.js
src/main.js

To make `window.open(uri).close()` we relied on bunch of fragile hacks that broke at some point. This patch removes some of the hacks and instead adds several tasks to make avoid platform limitations:
forceRender - Forces renderer to update DOM in the same tick (which is needs to be a case for mozbrowseropenwindow)
replaceElement(selector, element) - Replaces element matching passed query selector with passed element. It also copies over attributes, properties & event listeners from element being replaced.
forceReplace(selector, element) - Forces render in the same tick & replaced element
Patch also removes some of the obsolete code that has being long replaced by other tasks.

Fix connection between window & it’s opener

---

src/common/request-animation-frame.js
src/main.js

With this change if `raf=timer` query argument is passed, custom `setTimeout` based `requestAnimationFrame` implementation is used. This makes it possible to avoid overhead of `requestAnimationFrame` implementation currently present in servo. For details see: servo/servo#10050

Add option to use timer based requestAnimationFrame

---

package.json

New version of reflex has new task scheduler which was rewritten to dramatically reduce number of allocations performed during task execution. Before this change task scheduler was in top 5 allocation sights when profiling page load. After this change scheduler does not appear even in top 20 allocation sights whine profiling page load.
Unfortunately I don't think this has a significant impact on overall performance as far as I can tell, but it should help us reduce GC pauses overall.

Update to reflex 0.3

---

src/common/url-helper.js

Electron does not throw on `new URL(‘foo bar’)` which caused misbehavior on Electron.

Fix for `isNotURL` function on Electron.

---

src/browser/web-view.js
src/browser/web-view/moz-browser-frame.js

This change reverts d15d0ae as it was breaking layout on Electron & instead add's `display:block` to only `mozbrowser` iframes.

Iframe display block

---

src/devtools.js
src/main.js

New devtools code stores module it instruments in the model, this broke live reload as application is restored from last state which still used to point to old module code that has not changed.

Fix regression in live reloading.

---

src/driver/virtual-dom/index.js

Electron (& WebKit in general) does not dispatch `focus` / `blur` events on the document, it does on `window` instead. We are listening on `document` instead as it used to work in servo (see #1053) but it no longer does. This patch changes code back so we listen for top level events on window again, presumably servo/servo#9482 will fix it so that events are dispatched on window instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1064)

Listen for top level events on window.

---

src/browser/Sidebar/Toolbar.js

That button is now redundant as sidebar already has a "New Tab" tab that serves exact same purpose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1067)

Remove `+` button from sidebar.

---

src/about/newtab/newtab.js
src/browser/Navigators.js
src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/WebView.js
src/browser/Navigators/Navigator/WebView/Shell.js
src/browser/Sidebar/Tab.js

With this patch following changes are made:
1. `about:newtab` page sets a meta tag on theme changes to update titlebar so it matches the wallpaper.
2. `about:newtab` always has a input field displayed & it can't be dismissed.
3. `about:newtab` does not get's overlay when input is active.
4. It is not possible to close `about:newtab`.
5. Entering urls / search queries in `about:newtab` opens them in new tabs.
Please note this pull is based off #1065 there for it includes changes from there, in other words I'd just look at last two commits. Also all other pulls have being factored out from here and there for all changes are necessary to get expected experience.
P.S.: This is not the approach I would like to take, more specifically polluting Navigator with `isPinned` and `isInputEmbedded` …

Make interact with about:newtab different from regular tabs

---

src/about/newtab/tiles.json

It was pointing to our issues page instead for some reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1078)

Fix link for stackoverflow.com

---

src/about/newtab/main.css

There are clipping issue servo/servo#11562 in webrender that occurs when clipping rounder region with in the rounded region. This change removes border-radius on body that was rounder for no apparent reason & there for avoids above mentioned issues in webrender.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1076)

Fix tile clipping issues on servo

---

src/about/newtab/newtab.js

Doesn't remove any of the wallpapers infrastructure, but removes the switcher.
Fixes #1084.
r? @Gozala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1085)

Disable wallpaper switcher on about:newtab

---

src/browser/Navigators/Overlay.js

This workaround #1038 and servo/servo#11664 that prevents us from cancelling click events when force touch is handled. With this change we react to mousedown event instead of click which fixes our issue since overlay is not displayed when zoomed in & there for we avoid causing zoom-in at the end of force touch. clicks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1087)

Zoom in page on mousedown

---

src/browser/Navigators/Navigator/Assistant/search.js

I was getting many errors like:
```
Error: Network request to http://ac.duckduckgo.com/ac/?q=ip&type=list has failed:
Error: Network request to http://ac.duckduckgo.com/ac/?q=iph&type=list has failed:
Error: Network request to http://ac.duckduckgo.com/ac/?q=ipho&type=list has failed:
Error: Network request to http://ac.duckduckgo.com/ac/?q=iph&type=list has failed:
Error: Network request to http://ac.duckduckgo.com/ac/?q=ip&type=list has failed:
Error: Network request to http://ac.duckduckgo.com/ac/?q=i&type=list has failed:
```
and no search suggestions.
Using https seems to fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1096)

Use https when looking up search suggestions

---

src/browser/shell.js

Turns out VirtualDOM `thunk` does not like resolution to `””` and always expects node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1102)

Fix browser.html when using native titlebar.

---

src/browser/Navigators/Navigator.js

Animation can be enabled via tabswitch=xfade param.
Fixes #1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1114)

Disable cross-fade animation

---

src/browser/Navigators/Navigator.js

This mitigates #1099 issue. So problem was that as you type we query search service. If you submit input before suggestions come back, suggestions would pop up later in the process. In @paulrouget case it in the background `newtab` page so you see them when you switch back. I think what @metajack was observing is same bug, he just edits tab url and submits it before suggestions show up, but in this case suggestions popup on top of existing page because they are loaded in the same tab.
Now what this change does is it deactivates suggestions bar (a.k.a assistant) when input is submitted. So race is not fixed, suggestions still will get updated etc.. it's just they won't appear over the active or background tab because assistant itself is not going to be displayed. If you activate the input …

Disable assistant once location is submitted.

---

README.md
gulpfile.babel.js
main.js

Makes github work by changing a media query's result.
r? @paulrouget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1125)

Increase default vertical size to 740

---

README.md
gulpfile.babel.js

Without this change `escape` quits servo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1133)

Update preference for disabling key shortcuts.

---

src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/Assistant.js
src/browser/Navigators/Navigator/Assistant/history.js
src/browser/Navigators/Navigator/Assistant/search.js

This fixes #1099. Unlike workaround in #1115 this actually resets assistant when input is submitted. Assistant on reset aborts all pending queries, there for late suggestions will no longer be added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1138)

Abort search queries when input is submitted.

---

src/about/newtab/demos/transparent_rects.html

Who'd ever need more than 500 rects?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1143)

Set rect count in Transparent Rects demo to a saner value

---

gulpfile.babel.js

The js files with the evil ad demo were not being copied by gulp.
Hopefully this will be the last fixup here :wink:
Note: copying all `*.js` broke the newtab page, so I just have this copying the js for the evil ad demo only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1142)

Copy evil ad js to dist

---

src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/Assistant.js
src/browser/Navigators/Navigator/Assistant/search.js
src/browser/Navigators/Navigator/Input.js
src/driver/virtual-dom/index.js

There were set of issues related to the input field:
Fixes #1157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1166)

Fix input updates so that content does net get's messed up when typing quickly 

---

src/browser/Sidebar/Tabs.js

browser.html master works great on gecko once you do rm -rf node-modules and re run everything from scratch...
I just have this very tiny fix. I don't know if this `overflow-y: scroll` is very important on Servo,
but it makes the scrollbar always visible on Gecko. Which looks very ugly on Windows.
And not setting anything for `overflow-x` also makes the x-scrollbar always visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1168)

Fix always displayed scrollbars in tabs sidebar on Gecko.

---

src/browser/Navigators/Navigator/Input.js

Fixes #1171
With this change autocomplete behavior is more natural as `Shift+LeftArrow` selects last typed character, instead of unselecting part of the autocomplete.
Please note: This solves issue on the app side. With this change it will behave as expected on Electron but issue will still be present in servo until https://github.com/servo/servo/issues/12300 is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1172)

Autocomplete with backward selection.

---

src/common/devtools.js

Since mozsettings API does not exist in servo, error was logged into a console when attempt to query it was made. This change defers initialization of devtools hud until it is enabled, there for error will not show up unless you activate devtools hud manually.
Fixes #1153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1169)

Init devtools only when activated.

---

src/browser/Navigators/Navigator/Input.js

Fixes #1173
Change 8acb7fd started asserting search query to input value to only update input if query matched the value. This did not take into the account that suggested autocomplete is also part of value and there for changing suggestions would no longer update autocomplete.
This change amends original assertion and compares query only to unselected fragment of value so that completion selections do not affect the assertion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1174)

Fix regression that prevents suggestion to update autocomplete.

---

src/browser/Navigators/Navigator/Input.js
src/common/editable.js
src/common/text-input.js
src/driver/virtual-dom/index.js

Fixes #1176
Previous code was trying to avoid infinite selection update loop by comparing `previous` and `next` selection ranges and dropping updates if they were equal. This did not properly handled a case where input was updated with different value `value` but equal `selection` as selection update code would run before `select` event would occur. With this change selection change now is determined by comparing `next` selection range to an actual selection on the DOM element, avoiding both infinite loops and above mentioned issue.
This change also makes `selection` field mandatory on models as `null` selection makes things less deterministic and opens possibility for race conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix bug in selection update code.

---

src/about/repl/repl.js
src/browser/Navigators/Navigator/Assistant/history.js
src/common/prelude.js

With this changes to `merge` flow ensures that all fields of `patch` are type compatible with corresponding fields of the `model` being patched.
Second commit fixes all the mismatches made apparent by this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1180)

Improve type annotation of merge to catch more type mismatches.

---

src/common/editable.js

In #1180 type annotations of `merge` got improved to handle type mismatches. But #1178 introduced type mismatch that flow was unable to catch until #1180 fixed that. There for landing #1180 start reporting type mismatches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1181)

Fix type errors introduced by #1180 over #1178

---

package.json
src/about/settings/setting.js
src/browser/Navigators/Navigator/Assistant/search.js
src/browser/Navigators/Navigator/Assistant/title.js
src/browser/shell.js
src/common/keyboard.js
src/common/prelude.js
src/common/style.js
src/common/url-helper.js

- Update reflex-virtual-driver that failed on flow@0.28
- Use `toString()` in template string variables with non strings as required in flow@0.28.
- Add missing type annotations.
- Get rid off @FlowIssue suppression comments where possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1183)

Update to flow@0.28

---

electron-preload.js
main.js

Per the discussion in #1179, this re-enables `nodeIntegration` and runs a `preload` script to delete the node modules (roughly following what happens [here](https://github.com/electron/electron/blob/9f0fc96025fec8948eeb8ca45184891c3d8e485d/lib/renderer/init.js#L85)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1184)

Re-enable nodeIntegration; use electron preload

---

src/common/prelude.js

This utility helps including extra effects in the update step
```js
appendFX(Effects.perform(task), updateAThink(state, action))
```

Implement appendFX helper function.

---

src/common/prelude.js

Utility `port` function allows creation of endpoints to which `address` could be passed.
```js
export const onFocus = port(always({ type: “Focus” }))
html.input({ onFocus: onFocus(address) })
```
Idea is that `Port` instances could be shared and reused across modules.

Address port

---

src/common/prelude.js

Utility `anotate` function allows mapping ports such that resulting port will map it's messages via provided `tag` function:
```js
export const onFocus = port(always({ type: “Focus” }))
```
```js
import * as Focus from "./Focus"
const tagFocus = message => ({ type: "Focus", focus: message });
// P.S.: Same `tagFocus` is used with `fx.map(tagFx)` 
const onFocus = anotate(Focus.onFocus, tagFocus);
const view = (model, address) =>
html.input({ onFocus: onFocus(address) /*...*/ })
const update = (model, message) => {
switch (message.type) {
case "Focus":
return setFocus(model, Focus.update(model.focus, message.focus));
/* ... */
}
}
```

Address port anotate

---

src/common/editable.js
src/common/focusable.js

Editable and Focusable are implemented as interfaces or components that you need to mix in. This a step towards making them more standard components that can be embedded pretty much like all other components are.

Make Editable and Focusable embeddable.

---

src/about/settings/setting.js
src/common/editable.js
src/common/focusable.js
src/common/text-input.js

Refactor TextInput to embed `Focusable`, `Editable`, `Control` instead of mixing them in.

Refactor `TextInput` to avoid mixins.

---

src/about/settings/setting.js
src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/Input.js
src/common/editable.js
src/common/focusable.js
src/common/text-input.js

Refactor `Input` to embed `Focusable`, `Editable` instead of mixing them in.

Refactor `Input` to avoid mixins.

---

src/common/button.js
src/common/control.js
src/common/target.js
src/common/toggle.js

Embed `Control`, `Target` & `Focus` modules instead of mixing them in.

Refactor `Button` to avoid mixins

---

src/browser/Navigators/Navigator/Input.js
src/common/button.js
src/common/focusable.js
src/common/text-input.js
src/common/toggle.js

Make `Focus` implementation monomorphic.

Make `Focus` implementation monomorphic.

---

src/common/button.js
src/common/target.js
src/common/toggle.js

Make `Target` implementation monomorphic.

Make `Target` implementation monomorphic.

---

src/browser/Navigators/Navigator/Input.js
src/common/editable.js
src/common/text-input.js

Make `Editable` implementation monomorphic.

Make `Editable` implementation monomorphic.

---

src/browser/Navigators/Navigator/Assistant/Selector.js

Module provides generic `Selector` component similar to `<select>` which is completely decoupled from options it operates on. This patch intentionally only adds this module without using it (which is done in #1185) to reduce the number of changes in #1185

Implement generic Selector module.

---

src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/WebView.js
src/browser/Navigators/Navigator/WebView/ElectronFrame.js
src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
src/driver/virtual-dom/index.js

Set visibility on/of if frame is / isn’t selected.
First commit also adds a generic hook into virtual-dom, that runs a task with corresponding DOM element and passed value to do custom modifications when patch is applied.
I have being testing this feature via command:
```
/Applications/Servo.app/Contents/MacOS/servo -w -b --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref  shell.builtin-key-shortcuts.enabled=false http://localhost:6060\?url\=https://Gozala.jsbin.com/mudum
```
Open tab increments number on animation frames, so if you switch to other tab it will stop incrementing & resume when you're back.
P.S.: I will do a followup to use same `setting` hook for other workarounds we currently have.

Use iframe.setVisibile on mozbrowser iframes

---

src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/WebView.js
src/browser/Navigators/Navigator/WebView/ElectronFrame.js
src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
src/common/keyboard.js
src/driver/virtual-dom/index.js
src/driver/virtual-dom/index.js.flow

This change follows up on #1213 so please ignore first two commits. It also does two changes:
1. Creates `index.js.flow` so flow can ensure that `@driver` module is used properly.
2. Special `Abort` type is replaced with `null` which aborts feeding event back into update loop. This change was done as otherwise type annotations were becoming too complex and was not worth it.

Provide type annotations for @driver module

---

README.md
gulpfile.babel.js

Resolution is not necessary anymore as the default window size has
changed.
-M -S enable multiprocess and sandboxing.

Update servo options.

---

.bin/deploy.sh

I haven't tested, but that should do it.
Once this is done, we'll update Servo to not use a numbered revision but the head of the crate branch.

Deploy on each revision

---

build.rs

On windows, if we're building without a full msys-like environment, we can't do cp -r.  This has build.rs use xcopy in this case.

Use xcopy on windows

---

src/browser/Navigators/Navigator.js
src/browser/Navigators/Navigator/WebView/ElectronFrame.js
src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
src/browser/Navigators/Navigator/WebView/Navigation.js
src/browser/Navigators/Navigator/WebView/Util.js

We used to keep track `src` and currently loaded `url` as separate fields in the model so that we would only update `src` when user edited url. But that logic had a major issue #949:
If user initial loads url `a` than navigates to `b` by clicking a link and then edits url to navigate to `a` nothing would happen. That is because Virtual DOM would diff and see that src in both cases is `a` and do not update `iframe.src`.
With this change we use `setting(location, url)` for updating `iframe.src`. As of `location` setter it keeps track of iframe location and only reflects passed `url` if it is different from it.
This approach fixes #949 and makes state model simpler.

Workaround iframe API limitations at the DOM level.

---

gulpfile.babel.js
package.json

This needs to just be for msvc, as for mingw dir paths get specified using mingw syntax. Sigh.

Use xcopy only with msvc target, as dir paths are different with mingw

---

src/browser/Navigators/Navigator/WebView.js
src/browser/Navigators/Navigator/WebView/Page.js
src/browser/Navigators/Navigator/WebView/Page/Icon.js
src/browser/Navigators/Navigator/WebView/Page/Sign.js
src/browser/Navigators/Navigator/WebView/Util.js
src/browser/Sidebar/Tab.js
src/common/favicon.js
src/common/image.js

Now with pages that don't have favicon you'll see generated icon that has background of a site `theme-color` (see [mozbrowsermetachange](https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowsermetachange) event for more details) and a contrasting foreground color.
Unfortunately [`mozbrowsermetachnage`](https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowsermetachange) events don't seem to be dispatched in servo so colors default dark gray over warm white. Once events will be dispatched this code will take advantage of it.
Unfortunately due to https://github.com/servo/servo/issues/12885 `onerror` events on images aren't fired in servo there for in some cases tabs will have no fallback icons, as we will try to load unavailable image but will never discover it was not available …

Implement fallback icons

---

package.json
src/About/Newtab/Newtab/Wallpapers.js

Reformat [About/Newtab/Newtab/Wallpapers.js] to StandardJS Style (#1242)

---

README.md

The previous anchor didn't resolve to anything (anymore?). Changed it to what seemed the most likely appropriate target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1268)

Fix broken link to pre-requisites
