browserhtml/browserhtml

README.md
=> Add a short blurb about WebIDE in the readme.

.gitignore
Can @paul or @gordonbrander  take a look at this.
=> Make sure git does not ignore required modules.

css/locationbar.css, css/navbar.css, css/theme.css
Introducing snap points. More work is required for scroll operations not triggered by the wheel.
Resolves #55.
=> Add CSS snap points

node_modules/browser/actions.js, node_modules/browser/browser.js, node_modules/browser/index.js, node_modules/browser/navigation-panel.js
- Show tabstrip if >1 tab & input is hover.
- Show tabstrip if >1 tab & ctrl+tab / ctrl+shift+tab is pressed.
- Hide tabstrip if <1 tab.
- Hide tabstrip if ctrl is released.
- Hide tabstrip if kill zone is hovered.
=> Tab switch interaction tweaks #81, #82

css/theme.css
This fixes the way we style hidden attributes, see more details in #77 
@paulrouget wanna take a look at this ?
=> Handle `hidden` attribute properly.

node_modules/browser/actions.js, node_modules/browser/web-viewer.js, node_modules/browser/web-viewer/actions.js
@Gozala For some reason, the built iframe is rendered as `<iframe hidden="">` instead of `<iframe hidden="true">`. Any idea why? `hidden=true` is normally used when `toggle` is used.
=> support onOpenWindow

css/locationbar.css, css/tabstrip.css, css/theme.css, css/window_controls.css, src/browser/browser.js, src/browser/index.js, src/browser/navigation-panel.js, src/browser/theme.js, src/browser/web-viewer.js, src/browser/web-viewer/actions.js
New commit on top of master, incorporating suggestions from
https://github.com/mozilla/browser.html/pull/67
=> Add hardcoded color themes

.jscsrc, src/browser/actions.js, src/browser/browser.js, src/browser/core.js, src/browser/deck.js, src/browser/deck/actions.js, src/browser/editable.js, src/browser/element.js, src/browser/embedding.js, src/browser/focusable.js, src/browser/iframe.js, src/browser/index.js, src/browser/keyboard.js, src/browser/navigation-panel.js, src/browser/page-switch.js, src/browser/page-switch/actions.js, src/browser/theme.js, src/browser/web-viewer.js, src/browser/web-viewer/actions.js, src/shims/immutable-cursor.js, src/shims/omniscient.js
This is essentially #101 + fix for this comment https://github.com/paulrouget/browser.html/commit/7bd1ce597cccc9f8f2d7241ac03c90f00a77af33#commitcomment-9828592
=> Clarity #101 + Fix for securityState update

src/browser/navigation-panel.js, src/browser/theme.js
=> Fix ellipsis color matching in location bar

src/browser/actions.js, src/browser/browser.js, src/browser/index.js
Fix for the #107 @paulrouget @gordonbrander can one of you take a look ?
=> Implement session restore

css/navbar.css, css/tabstrip.css
Fixes #132 
@gordonbrander - It looks like there was already a 200ms transition elsewhere in the codebase, so I went with the same here. Thoughts?
I'm also having trouble with cache invalidation and using the HTTPServer here. Do you guys have any suggestions for that?
=> Animate background color for tabstrip and navbar.

css/tabstrip.css, main.js, src/browser/actions.js, src/browser/browser.js, src/browser/core.js, src/browser/deck.js, src/browser/deck/actions.js, src/browser/keyboard.js, src/browser/navigation-panel.js, src/browser/page-switch.js, src/browser/web-viewer.js, src/browser/web-viewer/actions.js, src/lang/functional.js, src/shims/omniscient-dispatch.js, src/shims/omniscient.js
This pull is **WORK IN PROGRESS** implementation of tab switch preview described in #82 that updates address bar and active tile but only switches tab on key release.
Publishing it earlier so that @gordonbrander can play around with it to see how it feels. I don't find this behavior more pleasant.
=> Work in progress tab switch on release

css/tabstrip.css, src/browser/page-switch.js
=> Implement close button for tabs.

css/theme.css, src/browser/browser.js
Different option for fixing #108
=> Prevent scroll if input is focused.

css/locationbar.css, src/browser/navigation-panel.js
Fixes https://github.com/mozilla/browser.html/issues/167.
=> Move progress bar out of location bar. Fixes #167

src/browser/actions.js, src/browser/browser.js, src/browser/navigation-panel.js, src/browser/progressbar.js, src/browser/web-viewer.js, src/browser/web-viewer/actions.js
@Gozala , I was thinking, can't we just pass the whole state to each component? Every time we add a new parameter, it makes lines larger, and we have to add the parameter to all the parents.
=> Do not store progress at the viewer level

css/dashboard.css, css/tabstrip.css, css/theme.css, index.html, src/browser/actions.js, src/browser/browser.js, src/browser/dashboard.js, src/browser/web-viewer.js
Squashed and cleaned up dashboard commits. Fixes https://github.com/mozilla/browser.html/issues/151.
=> Add hardcoded dashboard

css/tabstrip.css
Increase border size. Fixes https://github.com/mozilla/browser.html/issues/199. @Gozala can you review?
=> Increase border size on close button

src/browser/navigation-panel.js, src/browser/web-viewer.js, src/browser/web-viewer/actions.js
It makes the awesomebar behave better, and also how Firefox Desktop works.
=> Store user input at the webviewer level

css/awesomebar.css, src/browser/actions.js, src/browser/awesomebar.js, src/browser/navigation-panel.js
=> navigate through the awesomebar with keys

src/browser/actions.js
=> Start with dashboard.

src/browser/actions.js, src/browser/browser.js, src/browser/editable.js, src/browser/keyboard.js, src/browser/navigation-panel.js
=> Use keybindings in awesomebar.

css/tabstrip.css
=> Update tabstrip to same clipping approach as tiles

src/browser/core.js, src/browser/keyboard.js
That way I can for example I could define function that would log subpart of state I'm interested on every change, or even have conditionals to log only when entering a broken state etc..
=> Implement a better debugging support.

css/theme.css, src/browser/actions.js, src/browser/browser.js, src/browser/web-viewer.js
This is a workaround fix for #266
=> Fix tiles on refresh.

src/browser/browser.js
(even on Dashboard) Fixes #246.
=> Show tabstripkillzone when Awesomebar is active

main.js, src/browser/actions.js, src/browser/awesomebar.js, src/browser/browser.js, src/browser/core.js, src/browser/dashboard.js, src/browser/editable.js, src/browser/index.js, src/browser/navigation-panel.js, src/browser/page-switch.js, src/browser/progressbar.js, src/browser/web-viewer.js, src/shims/immutable-cursor.js
This is basically a one of the changes described under #250 
@paulrouget could you take a look ? @gordonbrander maybe you can also take a look and try to make sure I have not broke anything. In my tests seems to work fine.
=> This removes all the cursors

README.md
=> README: Link to Servo

src/browser/util/url.js, src/browser/web-viewer.js
@fabricedesre can you take a look?
=> use window.URL in url.js

main.js, package.json, src/browser/actions.js, src/browser/awesomebar.js, src/browser/navigation-panel.js
Right now this just updates awesome bar as it was simplest to update.
=> Illustration of how we could use records to model structured state

src/browser/browser.js
=> Reset selected tab when moving mouse out of tabstrip

css/theme.css
=> Make sure address-bar can't be in semi visible position.

src/browser/actions.js
=> Fix session store regression #346

src/browser/web-view.js
=> Fix flickering scrollbars #193

src/browser/browser.js, src/browser/main.js, src/common/element.js
This is not working for now. Depends on Part 8 of bug 1134106. Will fix #342.
=> command line handler

src/browser/web-preview.js, src/service/history-worker.js, src/service/scraper.js, src/service/thumbnail.js
Improvements to scraper results and card styles.
=> WIP Card and scraper improvements

src/browser/browser.js, src/browser/web-preview.js, src/service/scraper.js, src/service/thumbnail.js
More work on cards and scraper
=> Further improvements to preview cards

src/browser/theme.js, src/browser/web-preview.js
The defaults don't match the design.
=> Fix color of loading bar and preview highlight

src/browser/synthesis-ui.js, src/browser/web-input.js, src/browser/web-preview.js, src/service/gesture.js
- Wire up zoom in / out gestures.
- Wire up new tab button.
- No longer switch from create to edit mode to match spec.
=> Synthesis interaction

src/browser/web-view.js
...by special-casing delegation of ZoomIn and ZoomOut actions
=> Fix ZoomIn and ZoomOut

src/browser/web-view.js
=> fix overflow

src/browser/synthesis-ui.js, src/service/gesture.js
=> pinch should not show the awesomebar, and unpinch should show the webview

src/browser/synthesis-ui.js
Fixes typo from https://github.com/mozilla/browser.html/pull/491/files#r34635026.
=> Fix typo from pull 491

src/browser/web-view.js
=> Fix the open tab.

src/browser/browser.js, src/browser/theme.js
Fixes https://github.com/mozilla/browser.html/issues/510.
=> Set dashboard theme when on dashboard

src/browser/web-page.js, src/browser/web-preview.js, src/browser/web-view.js, src/common/favicon.js
=> Favicon selection mechanism

src/browser/browser.js, src/browser/location-bar.js, src/browser/suggestion-box.js, src/service/suggestion.js
Fixes https://github.com/mozilla/browser.html/issues/513
=> Fix suggestion box

src/service/gesture.js
Fixes https://github.com/mozilla/browser.html/issues/532.
=> Fix pinch sensitivity

src/browser/synthesis-ui.js
Fixes https://github.com/mozilla/browser.html/issues/530.
=> Fix bug with hitting esc when no webviews

css/theme.css, src/browser/browser.js, src/service/pallet.js
Reverses colors of box for color themes. Also changed hardcoded themes, since we do monochromatic themes now.
=> Fix location bar theming for dark color themes

src/browser/location-bar.js, src/browser/suggestion-box.js, src/browser/synthesis-ui.js
Follow-up for https://github.com/mozilla/browser.html/issues/513... a case I missed where location bar is focused, but you haven't typed anything yet.
Fixes https://github.com/mozilla/browser.html/issues/539.
Fixes https://github.com/mozilla/browser.html/issues/537.
Fixes https://github.com/mozilla/browser.html/issues/540.
Fixes https://github.com/mozilla/browser.html/issues/545.
=> Fix location bar styling when value is ''

src/browser/suggestion-box.js
=> replace collapse with display:none

src/browser/web-preview.js
See https://github.com/mozilla/browser.html/issues/558#issuecomment-130446507
=> Use camel case to suppress warnings from react.

src/browser/synthesis-ui.js
Issue occurs when trying to load suggested url.
=> Fix regression introduced by #572

src/browser/web-loader.js, src/browser/web-progress.js, src/browser/web-view.js, src/common/history.js, src/service/history-worker.js
=> Fix #574 regressions affecting history-db

gulpfile.js, package.json
This is useful if one doesn't use Graphene
=> Add build-server rule

src/browser/suggestion-box.js
=> Fix suggestion-clicks.

src/browser/web-preview.js
This makes them feel like tiny windows and helps with "recognition over
recall".
=> Theme preview headers

src/browser/web-view.js
=> Fix regression in load introduced by #572

src/service/pallet.js
Let's add a colors for github to the curated list otherwise their theme color is just annoyingly odd and makes us feel stupid.
=> add github to curated sites list.

src/browser/iframe.js
=> Fix regression in cmd-click introduced by #569

src/browser/suggestion-box.js
Follow-up to https://github.com/mozilla/browser.html/pull/596. Fixes styles.
=> Top hit follow-up

src/browser/suggestion-box.js, src/service/search.js
=> Fix suggestion flicks

src/browser/synthesis-ui.js, src/browser/web-view.js
Fixes https://github.com/mozilla/browser.html/issues/576.
@paulrouget r?
=> Allow location edit for different domains

src/browser/synthesis-ui.js, src/common/selector.js
=> Fix 0 tab case.

src/browser/web-view.js
=> Tab selection on close was getting messed up.

src/browser/web-preview.js
Fixes regression introduced by
https://github.com/mozilla/browser.html/pull/617.
=> Align card text left

src/browser/web-view.js, src/common/url-helper.js
=> Fix blank uri handling.

src/browser/iframe.js, src/browser/main.js, src/browser/suggestion-box.js, src/browser/web-loader.js, src/browser/web-preview.js, src/browser/web-view.js, src/common/editable.js, src/common/element.js, src/common/focusable.js, src/common/url-helper.js, src/service/scraper.js, src/service/thumbnail.js
=> Fix the race condition with incorrect loads.

package.json, src/browser/location-bar.js, src/browser/suggestion-box.js, src/common/url-helper.js, src/lang/functional.js, src/service/history-worker.js, src/service/suggestion.js
=> Retain selected suggestion across suggestion updates.

README.md
Solves: https://github.com/mozilla/browser.html/issues/668
=> README update - specifying node version

gulpfile.babel.js, npm-shrinkwrap.json, package.json
Note it is also that livereactload was failing to install on > node@4
=> Ditch react tailored JS transforms in favor of general hotreloader

src/browser/assistant.js, src/browser/web-view.js, src/common/history.js, src/common/style.js, src/common/url-helper.js, type/common/history.js
=> Assistant views

src/browser/input.js
This helps us easily pick out elements in view-source
=> Change keys for className in input view

src/browser/browser.js
Also add `Assistant.view` to views rendered.
=> Re-arrange browser sub-views for stacking reasons

src/browser/sidebar.js
Fixes overlapping image problem.
=> Fix sidebar favicons

src/browser/web-view.js
=> Fix reference to focus function

src/browser/sidebar.js
=> Hook up tab click actions

src/browser/browser.js, src/browser/overlay.js, src/browser/perspective-ui.js, type/browser/browser.js, type/browser/overlay.js
=> Add overlay model and view (WIP)

src/browser/perspective-ui.js
This adds the ability to hit esc to get out of create-web-view.
=> Esc create-web-view -> show-web-view

src/browser/input.js
=> Fix input styling in Servo

src/browser/browser.js
Workaround for https://github.com/servo/servo/issues/8754
=> Workaround vw/vh resizing issue in Servo

css/theme.css, src/browser/assistant.js, src/browser/overlay.js, src/browser/perspective-ui.js, src/browser/web-views.js
https://github.com/servo/servo/issues/8754
=> More workarounds for servo/#8754

README.md
=> Fix note about Node dep

README.md
=> Fix note about Node version

src/browser/sidebar.js
This changes the select color on tabs to blue.
=> Change select color to blue

README.md
Fixes https://github.com/mozilla/browser.html/issues/798.
=> Add browser gif to README

src/browser/perspective-ui.js, src/browser/sidebar.js, src/browser/sidebar/tab.js, src/browser/web-view.js
Will land a follow-up PR for the last item.
Fixes https://github.com/mozilla/browser.html/issues/789
=> Add close button to tabs

src/browser/browser.js, src/browser/index.js, src/browser/perspective-ui.js, src/browser/shell.js, src/browser/shell/controls.js, src/browser/updater.js, src/common/devtools.js, src/common/runtime.js, src/common/settings.js, src/common/url-helper.js, type/browser/updater.js, type/common/runtime.js
=> Fix updater module & enable it.

src/common/runtime.js
=> Remove debug statement.

gulpfile.babel.js, src/about/settings/index.html, src/about/settings/main.js, src/about/settings/setting.js, src/about/settings/settings.js, src/common/button.js, src/common/control.js, src/common/devtools.js, src/common/editable.js, src/common/prelude.js, src/common/settings.js, src/common/text-input.js, src/common/url-helper.js, type/about/settings/setting.js, type/common/button.js, type/common/control.js, type/common/prelude.js, type/common/settings.js, type/common/text-input.js
=> Implement about:settings API.

package.json, src/common/devtools.js
Fixes #828
Update virtual-dom-driver which fixes issue by preferring DOM Property checked over an attribute.
=> Fix checkbox not updating in some cases.

src/browser/sidebar.js, src/browser/sidebar/tab.js, src/browser/sidebar/tabs.js, src/browser/sidebar/toolbar.js
Fixes https://github.com/mozilla/browser.html/issues/844.
=> Rework sidebar dimensions to 8px grid

src/browser/perspective-ui.js
=> Revert incorrect changes that affected tab selector.

src/browser/assistant.js, src/browser/assistant/group.js, src/browser/assistant/history.js, src/browser/assistant/icon.js, src/browser/assistant/page.js, src/browser/assistant/search.js, src/browser/assistant/suggestion.js, src/browser/assistant/title.js, src/browser/assistant/top-hit.js, src/browser/assistant/url.js, src/browser/browser.js, src/browser/input.js, src/browser/web-views.js, src/common/selector.js, type/browser/assistant.js, type/browser/assistant/group.js, type/browser/assistant/history.js, type/browser/assistant/icon.js, type/browser/assistant/page.js, type/browser/assistant/search.js, type/browser/assistant/suggestion.js, type/browser/assistant/title.js, type/browser/assistant/top-hit.js, type/browser/assistant/url.js, type/common/decoder.js
Initial patch will just add search suggestions.
=> Search suggestions

src/browser/web-view.js
=> Fix crossfade in selection transition

src/browser/sidebar/tab.js
=> Animate close button on tabs (fix #802)

css/theme.css, src/browser/assistant.js, src/browser/assistant/icon.js, src/browser/input.js, src/browser/web-view.js
Fixes some style issues with Assistant and fonts in El Capitan. Also updates a few details to bring Browser.html closer to the actual design comps.
Fixes #504.
=> Fix El Cap style issues

src/browser/browser.js
This informs the user that the pin button will pin the sidebar. Fixes https://github.com/browserhtml/browserhtml/issues/888.
=> Transition to show-webview when pinning sidebar

src/browser/web-view.js, src/browser/web-view/progress.js, type/browser/web-view/progress.js
Don't merge quite yet. Gonna improve the animation just a bit.
Fixes https://github.com/browserhtml/browserhtml/issues/839.
Fixes https://github.com/browserhtml/browserhtml/issues/882.
Fixes https://github.com/browserhtml/browserhtml/issues/880.
=> Implement multi-phase progress bar animation

src/browser/web-view/util.js, src/browser/web-view/util.js.flow, type/browser/web-view.js
=> Fix the favicon fallback handling.

gulpfile.babel.js, index.html, src/about/repl/index.html, src/about/settings/index.html, src/common/url-helper.js
Fixes regression for about pages introduces by # #890
=> Fix about pages for new dist config.

.bin/deploy.sh, .gitignore, gulpfile.babel.js, package.json
@paulrouget can you take a look if it looks alright to you ?
=> Update deployment script to generate cargo crates

src/common/url-helper.js
=> Fix typo when reading about url

gulpfile.babel.js
=> Include manifest.webapp in build

src/browser/assistant/search.js, src/browser/input.js
Fixes #869
This fix is more of a hack than a proper fix, but it does make input usable.
=> Resolve the issue with forced input replacement

gulpfile.babel.js
@metajack how does this look like ?
=> Strip out `.` from cargo package name.

docs/architecture.md
Spelling fix in architecture.md.
=> Fix "incerement" misspelling.

src/browser/browser.js, src/browser/sidebar.js, src/browser/sidebar/tab.js, src/browser/sidebar/toolbar.js
Flattened version of https://github.com/browserhtml/browserhtml/pull/950. cc @paulrouget
=> Make colors less opinionated

package.json
=> eased version update

css/theme.css, src/browser/index.js, src/browser/shell.js, src/common/runtime.js
=> Only show controls on Mac

.bin/deploy.sh, package.json
Deploying new version no longer wipes out previously deployed version. Fixes servo/servo#10170
=> Make deployment script incremental

src/browser/browser.js, src/browser/web-views.js
Fixes https://github.com/browserhtml/browserhtml/issues/968.
@paulrouget r?
=> Size webviews to width/height of container

package.json, src/browser/browser.js, src/browser/index.js, src/common/devtools.js, src/common/devtools.js.flow, src/common/runtime.js, src/common/runtime.js.flow, src/common/url-helper.js, src/common/url-helper.js.flow, src/devtools/playback.js
`cmd-alt-3` will dump a command into terminal invoking which will write a state snapshot file into disk & start a browser.html with it in a state snapshot was taken.
For example you can run following into your terminal (presumes PWD is project root):
```
echo '{"version":"0.1.5","mode":"create-web-view","shell":{"isFocused":true,"isMinimized":false,"isMaximized":false,"controls":{"close":{"isDisabled":false,"isFocused":false,"isActive":false,"isPointerOver":false,"text":""},"minimize":{"isDisabled":false,"isFocused":false,"isActive":false,"isPointerOver":false,"text":""},"toggle":{"isDisabled":false,"isFocused":false,"isActive":false,"isPointerOver":false,"isChecked":false,"text":""}}},"input":{"value":"amazon","isFocused":true,"isVisible":true,"selection":{"start":2,"end":6,"direction":"f …
```
=> Implement record / replay tool for browser.html

index.html
Fixes regression introduced by #989
=> Fix the url to the main js bundle.

src/common/keyboard.js
Lot of our keybindings were triggered on keyup / keydown and polyfill was only handling keypress. This fixes bunch of keybindings for Electron.
=> Improve keyboard bindings polyfill

CONTRIBUTING.md, docs/architecture.md, package.json
=> Change all github links from mozilla/browser.hml to browserhtml/browserhtml

src/browser/input.js
Until https://github.com/servo/servo/issues/10561 is fixed.
=> grey placeholder workaround

src/devtools/record.js, src/devtools/replay.js
1. Record tool flashes UI when you print / publish snapshot and displayed message telling you that.
2. Replay tool displays message informing that it is: loading loading snapshot or failed to load snapshot.
3. Utilizes thunks to reduce overhead of tools when not in active use.
=> Add some UI to record & replay devtools.

src/browser/web-view.js, src/browser/web-view/navigation.js, src/browser/web-view/page.js, src/browser/web-view/progress.js, src/browser/web-view/security.js, src/browser/web-view/shell.js
=> Change long ternary chains to switch statements in web-view-related files

src/browser/assistant/history.js, src/browser/assistant/search.js
embed was terrible choice that also happened to not work on Electron.
=> Use section elements instead of embed.

src/browser/shell/controls.js
A button is 12px large. The last button is 40px from the left. 40 + 12  = 52.
=> avoid container overflow

src/browser/shell/controls.js, src/browser/web-view.js
fixes #1012 and brings back the progressbar.
=> Iframe is block

src/about/repl/repl/host/window.js, src/browser/assistant/history.js, src/browser/assistant/search.js, src/browser/pallet.js, src/browser/web-view/shell.js, src/common/runtime.js, src/common/settings.js
I'm taking over #1003 since I got no response from contributor for a while. This patch based over #1003 but it also addresses review comments made there.
=> Task.future

README.md, gulpfile.babel.js
=> Update Servo cli options

src/browser.js, src/browser/Navigators/Navigator.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1052)
=> ShowTabs on force touch

src/browser.js
r? @paulrouget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1061)
=> Remove browser-action log spam

src/browser/Navigators/Navigator.js, src/browser/Navigators/Navigator/WebView.js, src/browser/Navigators/Navigator/WebView/Shell.js
Fixes #1058
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1065)
=> Dismiss Input / Assistant when WebView is focused

README.md, gulpfile.babel.js, main.js
800x600 is very small - even the tiny Macbooks show much more. Let's increase this to something more reasonable.
r? @paulrouget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1072)
=> Increase default window size

README.md
A more specific explanation of how to get things working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1080)
=> Clear instructions, easy implementations.

src/about/newtab/newtab/tile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1079)
=> Open tabs with rel="noopener noreferrer"

src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
@paulrouget wanted this change as Servo is also changing over to URL https://github.com/servo/servo/issues/11450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1092)
=> URI to URL

README.md, gulpfile.babel.js
Because https://github.com/servo/servo/pull/11735/files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1098)
=> new pref name

src/browser.js
Not 100% sure of these changes, but it works :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1104)
=> Add cmd-q shortcut to quit

src/about/newtab/tiles.json, src/browser/Navigators/Navigator/Assistant/search.js, src/common/url-helper.js
Fixes #1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1113)
=> Switch to HTML version of DDG.

src/browser/Navigators/Navigator.js
Fix #1119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1120)
=> make unselected iframe hidden

src/browser/Navigators/Navigator.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1121)
=> use rounded borders only on osx

.bin/deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1122)
=> Sort tags per date

.bin/deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1124)
=> better way to get latest tag

src/browser/Sidebar/Tab.js
r? @paulrouget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1123)
=> Use pointer cursor for tabs in sidebar

package.json
r? @gozala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1130)
=> Update reflex-virtual-dom-driver to 0.2.1 to disable slow frame warning

src/about/newtab/demos/LICENSE, src/about/newtab/demos/menus.html, src/about/newtab/demos/moire.html, src/about/newtab/demos/spheres.html, src/about/newtab/demos/spinning.html, src/about/newtab/demos/transparent_rects.html, src/about/newtab/tiles.json
Fixes #1131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1132)
=> Bundle servo demos.

src/browser/Navigators.js
Fixes #1128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1134)
=> Show web view on tab activation.

src/browser/Navigators/Navigator.js, src/browser/Navigators/Navigator/Assistant.js, src/browser/Navigators/Navigator/Assistant/history.js, src/browser/Navigators/Navigator/Assistant/search.js, src/browser/Navigators/Navigator/Assistant/suggestion.js
Fixes #1127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1136)
=> Enable non keyboard interaction with assistant.

src/about/newtab/demos/moire.html
Temp fix for servo/servo#11939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1137)
=> Temporary fix for moire demo

src/browser.js, src/browser/IssueReporter.js, src/browser/Navigators.js, src/browser/Navigators/Navigator.js, src/browser/Navigators/Navigator/WebView.js, src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
Fixes #1001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1145)
=> Add an issue reporter UI.

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1146)
=> Version 0.1.12

package.json
Reverts browserhtml/browserhtml#1146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1147)
=> Revert "Version 0.1.12"

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1149)
=> Version 0.1.13

src/browser/IssueReporter.js, src/browser/Navigators/Navigator/WebView/MozBrowserFrame.js
Now that servo/servo#12136 has landed, we can include the current Servo version + commit hash in the issue reporter.
Fixes #1161
r? @Gozala 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1163)
=> Add servo version to generated issue reports.

src/browser/Navigators/Navigator/Input.js
Fixes #1167
With this change input changes do not query suggestion service if new value is included by a previous one, as we do not want to provide completions while user is deleting text. Once new character is typed new suggestions / completions will provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1170)
=> Stop querying suggestions on delete.

src/browser/Navigators.js
Fixes #1089 
Start servo with a url query parameter appended to the url, for example:  `../mach run -r -- -b -w --resolution=1024x740 --pref dom.mozbrowser.enabled --pref dom.forcetouch.enabled --pref shell.builtin-key-shortcuts.enabled=false http://localhost:6060?url=http://example.com
`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1187)
=> Support loading an initial URL

src/browser/Navigators.js, src/browser/Navigators/Navigator.js, src/browser/Navigators/Navigator/Overlay.js, src/browser/Navigators/Navigator/Progress.js, src/browser/Navigators/Navigator/WebView.js, src/browser/Sidebar.js, src/common/Animation.js, src/common/Deck.js, src/common/prelude.js, src/devtools.js, src/devtools/log.js, src/devtools/record.js, src/devtools/replay.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1193)
=> Factor out nofx function into prelude.

src/Service/History.js, src/Service/Search.js, src/browser/Navigators/Navigator/Assistant/History.js, src/browser/Navigators/Navigator/Assistant/Search.js
This change factors out IO stuff from `Search` and `History` modules into separate service modules.
=> Factor out services form the History and Search modules.

src/common/control.js, src/common/text-input.js
Make `Control` implementation monomorphic.
=> Make `Control` implementation monomorphic.

src/browser/shell/controls.js, src/common/button.js, src/common/toggle.js
Rename `Press` to `Click` to fix #1209
=> Clean up event hooks.

src/browser.js
=> Report non-pipeline panics

package.json, src/About/Newtab/Demos/evil_ad/physics/physics.js, src/About/Newtab/Demos/evil_ad/shared/dom.js, src/About/Newtab/Demos/evil_ad/shared/lib.js
=> Reformat Demos to StandardJS style (#1242)

package.json, src/About/Repl/Main.js, src/About/Repl/Repl.js
=> Reformat [About/Repl/] to StandardJS Style (#1242)

package.json, src/About/Newtab/Newtab/Wallpaper.js
=> Reformat [About/Newtab/Newtab/Wallpaper.js] to StandardJS Style (#1242)

package.json, src/About/Newtab/Main.js, src/About/Newtab/Newtab.js
=> Reformat [About/Newtab] to StandardJS Style (#1242)

package.json, src/About/Newtab/Newtab/Tile.js
=> Reformat [About/Newtab/Newtab/Tile.js] to StandardJS Style (#1242)

package.json, src/About/Newtab/Newtab/Tiles.js
=> Reformat [About/Newtab/Newtab/Tiles.js] to StandardJS Style (#1242)

index.html
Fix for servo/servo#14919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/browserhtml/browserhtml/1263)
=> Update path to a js bundle from an html file.
